---
output: github_document
---

# Lecture 9 - Linear Models II

For this week's data practical, please note that you should already have set up your GitHub account (from [week 1](../1_introduction/README.md)), which will have an initial README.md file in your repository's [root directory](https://en.wikipedia.org/wiki/Root_directory). The example in this course's repository is the syllabus file, which is named [README.md](../README.md).

Now create your Linear Mixed Model report. You should create the .Rmd file and edit it in RStudio and then knit the output file into an .md file. You have to download a dataset that you are interested in and you have to fit your data in a Linear Mixed Model or a Generalized Linear Mixed Model using the methods that we discussed in class.

Here a guideline for your report:

* Find a dataset that you are interested in
* Upload the .csv and check you data
* Formulate your hypothesis
* Which is it your Response variable?
* Which is it your Fixed Factor and your Random Effect?
* You will use a Linear Mixed Model or a Generalized Linear Mixed Model? (If needed, show the assumptions)
* Now fit your data in three different models
* Which model describes better your data? Explain
 
Remember to apply the general suggestion to your report:

* add an appropriate header (e.g., title, author, date, output format)
* add some headers and sub-headers

Have fun and try to make the report interesting for the reader! 
